lastname = input("Enter your lastname:")
firstname = input("Enter your firstname:")
age = int(input("Enter your age:"))
height = float(input("Enter yor height:"))
print(f"{firstname} {lastname}! Your age is {age}.")
print(type(lastname))
print(type(firstname))
print(age + 2)
print(height + 2)
